[build]
  publish = "site"
  command = "npm run build"
  environment = { GIT_LFS_ENABLED = "true" }

[[redirects]]
  from = "/*"
  to = "/app/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "geolocation=(), camera=(), microphone=()"
    Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"
